### ISSUE TITLE
`Location` in types is not a defined type. It appears to be, simply due to HTML/DOM type defs

### ISSUE THREAD

**Issue by Connoropolous** [holochain/holochain-client-js#159] opened 2023-01-01 19:00 UTC
https://github.com/holochain/holochain-client-js/blob/575dbc45d288ad88fecd4aada31ad89bd07679a0/src/api/admin/types.ts#L186

<img width="796" alt="Screenshot 2023-01-01 at 10 59 37 AM" src="https://user-images.githubusercontent.com/1409121/210181876-9929f2a4-4e04-4854-af57-ce35706d09c7.png">

This is unhelpful when trying to determine how to provide a path to a DNA for example

**Comment by Connoropolous** [comment] 2023-01-01 19:03
Also, the whole `AppRoleDnaManifest` type seems a bit out of sync with its Rust counterpart
https://github.com/holochain/holochain/blob/9b38b2d8405696af7b4ca739f28373bb76f7d1ae/crates/holochain_types/src/app/app_manifest/app_manifest_v1.rs#L65-L91

**Comment by jost-s** [comment] 2023-01-04 21:56
partly duplicate of #59

**Comment by Connoropolous** [comment] 2023-01-04 22:07
oh, yep!

**Closed as completed** 2023-01-11 20:51 UTC
Labels: bug
