### ISSUE TITLE
[BUG] `tweetnacl` library causes bundling issues in various configurations

### ISSUE THREAD

**Issue by pospi** [holochain/holochain-client-js#180] opened 2023-03-03 07:00 UTC
**Describe the bug**

This library is a very mature nodejs package (read: old & infrequently updated). Being in an older format can cause compatibility issues with more modern development environments and build tooling.

Presently it has become problematic in https://github.com/neighbour-hoods/applet-template/issues/9#issuecomment-1453063313. I wish I'd been tracking other times it has been an issue with bundlers, 'cos this is not the first time I've had to go into arcane Nodejs internals because of its presence in the stack.

**Expected behavior**

Developers shouldn't have to think about this module's compatibility with TypeScript, Rollup, Webpack, Web Dev Server, Babel, ESM modules or anything else. At least, not beyond the normal level of consideration that would apply to any other module being included in a project.

Could we try swapping it out for [tweetnacl-ts](https://www.npmjs.com/package/tweetnacl-ts) or another alternative with broader module compatibility?

**Comment by jost-s** [comment] 2023-03-03 17:55
Hi @pospi, to reproduce this problem and test with a replacement, can I set up a rollup and web dev server project and use tweetnacl in it? tweetnacl-ts is even older, but it promises TS and bundler support. I want to test that before making a decision.

**Comment by pospi** [comment] 2023-03-08 03:31
You should be able to, yeah- a WDS config similar to [this one](https://github.com/neighbour-hoods/applet-template/blob/feature/9-wds-fixes/ui/web-dev-server.config.mjs#L14) should reproduce (differently) the bug with or without the `commonjs` plugin active.

I don't know that `tweetnacl-ts` is such a great suggestion, either. I figure there are possibly other alternatives out there that cover the same signing functionality?

**Comment by jost-s** [comment] 2023-04-14 02:26
I can reproduce the problem, I believe. Running WDS with tweetnacl commonjs-rollup'd in the web-dev-server.config results in a "no default export in tweetnacl" error in the browser.
When changing the import of tweetnacl to `import * as nacl from "tweetnacl"`, it succeeds, but the properties of `nacl` are not present. Some CommonJS weirdness, I suppose, that I don't fully get.

I'm looking for a replacement that is compatible with ES modules.

**Comment by jost-s** [comment] 2023-04-21 22:47
I've found a great replacement for tweetnacl and it works well: https://www.npmjs.com/package/@noble/ed25519
ESM compatible and works in browser and Nodejs.

When trying the client in WDS, isomorphic-ws is giving me grief. It's somewhat semi-CJS/ESM. I'm looking for a fix and will then release the client as WDS-compatible ;-)

**Comment by jost-s** [comment] 2023-04-24 18:43
I've chimed in on the commonjs issue in the WDS repo https://github.com/modernweb-dev/web/issues/1700#issuecomment-1520651888

**Comment by jost-s** [comment] 2023-04-27 23:52
This has been a time-consuming endeavor, and it's still not working. I've submitted another issue with WDS because I can't even use `ws` with it. https://github.com/modernweb-dev/web/issues/2248

**Comment by jost-s** [comment] 2023-05-01 18:36
v0.14.0 is released with the replaced NPM package. I'll open a new issue for WDS compatibility, even though the JS client can only wait for the WDS issues to be fixed.

**Closed as completed by jost-s** 2023-05-01 18:36 UTC
