### ISSUE TITLE
Role and cell clone naming not documented or very clear

### ISSUE THREAD

**Issue by nphias** [holochain/holochain-client-js#222] opened 2024-01-19 14:17 UTC
indexing of clones. (rolename:integer) to make a "clone_id" is undocumented and a bit unclear
I think it would be useful to have a common unique field which abstracts above all cell types (stem, clone, provisioned)
to reflect a role instance (useful for DX in the UI eg dynamic store creation) . It could be just rolename.
the exisiting "name" field in all cells could continue to be used for user defined (optional) application logic
for example:

```
export interface StemCell {
    dna: DnaHash;
    name?: string;
    dna_modifiers: DnaModifiers;
    -> rolename: string
}
/**
 * @public
 */
export interface ProvisionedCell {
    cell_id: CellId;
    dna_modifiers: DnaModifiers;
    name?: string;
    -> rolename: string
}
/**
 * @public
 */
export interface ClonedCell {
    cell_id: CellId;
    clone_id: RoleName; -> rolename: string
    original_dna_hash: DnaHash;
    dna_modifiers: DnaModifiers;
    name?: string;
    enabled: boolean;
}
```

**Comment by nphias** [comment] 2024-01-19 14:21
related to closed issue: https://github.com/holochain/holochain-client-js/issues/161

**Comment by jost-s** [comment] 2024-01-22 15:46
Yeah, it's not well documented. As a developer you don't create clone ids. And using them only makes sense for local calls, because you cannot know the clone id of a specific clone cell in other conductors. The only reliable way of making remote calls is using the cell id.

The clone index is given by the conductor. It cannot be set by the developer. You could have a rolename as the clone id as you suggest, but it wouldn't be different from `name`.

**Comment by mattyg** [comment] 2024-07-24 15:40
I'm working with clone cells after a long hiatus. With fresh eyes, I'm remembering how painful I found the ergonomics:

1. Its weird that for a provisioned cell, the field is `role_name`, but for a clone cell the field is `clone_id`, even though they seem to be the same?
2. It's painful to have to conditionally check if your cell is `CellType.Provisioned` or `CellType.Cloned` every time you want to use any data within it. I would love to move all the common fields up to a higher-level object. I.e.

```
interface Cell {
  cell_id: CellId;
  name: string;
  role_name: string;
  dna_modifiers; DnaModifiers
  cell_type: CellType;
  cell_type_details: StemCell | ProvisionedCell | ClonedCell
}

```

3. Serde has an option to include the enum type as a separate field. We should use that for the cell type.

This should probably be changed in the holochain repo rather than the client lib.

**Comment by mattyg** [comment] 2024-11-12 19:35
Closing this as a duplicate of #3219 -- we'll address this in holochain and update the client accordingly.

**Closed as completed by mattyg** 2024-11-12 19:35 UTC
