### ISSUE TITLE
Allow overriding websocket timeout via env vars or config

### ISSUE THREAD

**Issue by pospi** [holochain/holochain-client-js#104] opened 2022-04-05 02:57 UTC
As per https://github.com/holochain/tryorama/issues/106 the current 15000ms limit is too low for larger apps, and causes installation failures in both the Holochain Launcher and in Tryorama.

**Comment by jost-s** [comment] 2022-05-10 02:21
@pospi I was mistaken and this can be fixed entirely in Tryorama.

It's actually not the timeout of the web socket per se, as while it's uploading the hApp file it's not timing out. The problem is when instantiating the `AdminWebsocket`. [The `timeout` parameter isn't passed on](https://github.com/holochain/tryorama/blob/develop/src/conductor.ts#L344). That results in the `requester` always using the default 15 sec timeout, and that timeout is not depending on web socket activity, but just a hard timer.

I'm closing this issue. We're about to release the next Tryorama version, with which I have successfully installed the HoloREA hApp bundle.

**Closed as completed by jost-s** 2022-05-10 02:21 UTC
Labels: bug

**Comment by jost-s** [comment] 2022-05-10 02:22
@abe-njama FYI
